name: 'GKE CI'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./learn-terraform-provision-gke-cluster

    # 1. Checkout the repository to the GitHub Actions runner
    # 2. Install terraform CLI
    # 3. Terraform validate
    # 4. Terraform init, state list, plan
    # 5. Conditionally run terraform apply (if merged to main)
    # 6. Conditionally run terraform destroy (if branch starts with 'destroy' AND merged to main)
    steps:
    - name: Debug
      run: |
        echo $github.event_name
        echo $github.base_ref
        echo $github.head_ref

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Init, State List, Plan
      run: |
        terraform init
        terraform state list
        terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Apply
      if: github.base_ref == 'refs/heads/main' && github.event_name == 'push' && startsWith(github.head_ref, 'destroy') != true 
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Destroy
      if: github.base_ref == 'refs/heads/main' && github.event_name == 'push' && startsWith(github.head_ref, 'destroy') == true
      run: terraform destroy -auto-approve
